### ISSUE TITLE
Define Swagger/OpenAPI for Cratey

### ISSUE THREAD

**Issue by stain** [eScienceLab/RO-Crate_Issues#65]

**Comment by stain** [comment]
Doug to figure out where to push his Swagger experiments

**Comment by douglowe** [comment]
I've decided to put this in the eScience github organisation for now: https://github.com/eScienceLab/rocrate-microservice-api

For long-term residency, I think it would be best in either [eScienceLab](https://github.com/eScienceLab/) or [ResearchObject](https://github.com/orgs/ResearchObject). The [federated analytics](https://github.com/orgs/federated-analytics) organisation is good for organising the current project, but it's probably not the best home if we are looking to create an RO-Crate microservice (Cratey, or otherwise named) which we can use across projects.

**Comment by ianhinder** [comment]
Match up with Cratey requirement documentation.

**Comment by stain** [comment]
https://github.com/eScienceLab/rocrate-microservice-api/blob/main/cratey-api.json to be updated to match https://github.com/eScienceLab/Cratey-Validator/tree/develop/app/ro_crates/routes?   @alexhambley and @douglowe to discuss as this could be done potentially automatically from Flask. See issue https://github.com/eScienceLab/Cratey-Validator/issues/5

**Comment by ianhinder** [comment]
Superseded by https://github.com/eScienceLab/Cratey-Validator/issues/5.
