### ISSUE TITLE
Set up joint RO-Crate email address

### ISSUE THREAD

**Issue by elichad** [eScienceLab/RO-Crate_Issues#71]
@stain has the power - need to decide which RO-Crate people to forward emails to

**Comment by stain** [comment]
Gandi which has `researchobject.org` now requires 6 EUR/month for email address, while 123 reg which has `ro-crate.org` similar  charges.. looking at if any existing domains can be used

**Comment by stain** [comment]
Forwarding was free it turns out. 

I created:

* contact()researchobject.org for steering committee @stain @ptsefton @CaroleGoble 
* ro-crate()researchobject.org for support @stain @elichad @ptsefton
* conduct()researchobject.org @stain @elichad 

Listed on https://www.researchobject.org/ro-crate/community#contact-us
